### ISSUE TITLE
UI Ugly

### ISSUE THREAD

**Issue by Logan-Fouts** [Logan-Fouts/PicPurge#11]
Even though I designed the UI I think its kinda ugly it could be reworked. Maybe we can work together in Figma to come up with a better more flexible design.

**Comment by wlauer3** [comment]
Okay, I think that is a good idea. I want to make the select agressivensss thing slide to the left and expand down with numbers to select (1-6) then with the new soace on the right i want to have like some examples of what would be considered a duplicate. Like, have some example photos change depending on how agressive the setting you pick is. Like "With this aggressiveness, this may be considered a duplicate". This would let the person using it to make sense of the agressiveness number instead of arbitrarily guessing

**Comment by Logan-Fouts** [comment]
Yeah that sounds Like a good idea. Do you think you want to take care of that or should I? That way we dont waist eachothers time lol. :+1:

**Comment by wlauer3** [comment]
I can try it.  If i run into problems I'll let you know

**Comment by Logan-Fouts** [comment]
for the most part fixed nowm im pretty happy with it at least to a point that i dont think its a problem
